# Runtime configuration for the MVP
fps_cap: 25
smoothing_alpha: 0.30
keep_intermediates: false

thresholds:
  min_squat_depth_angle: 95.0     # degrees
  valgus_dev_max: 0.12            # normalized lateral deviation
  trunk_angle_max: 45.0           # degrees from vertical at bottom

segmentation:
  hip_min_drop_norm: 0.08
  peak_prominence: 0.03
  min_rep_duration_s: 0.8
